name: Bug
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What's the problem?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: How can we reproduce this?
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen instead?
