name: Feature
description: Request a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why is this needed? What problem does it solve?
  - type: textarea
    id: implementation
    attributes:
      label: Suggested implementation
      placeholder: Any thoughts on how this could be implemented?
